<a href="https://colab.research.google.com/github/AbbySnt/EstadisticaAplicada_1990002/blob/main/Actividad3_YASH_1990002_EAG44_ago2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio de Pandas

Carga las 2 librerias que hemos visto a lo largo del curso junto con su "apodo"

numpy, y pandas

**Coloca tu nombre y matricula**

Nombre: Yessica Abigail Santiago Hernandez

Matricula: 1990002

1. Carga las librerias básicas

In [1]:
##### carga las dos librerias usadas (numpy, pandas )
import numpy as np
import pandas as pd

El siguiente comando importa un data frame desde un archivo csv de internet

In [26]:
 ventas = pd.read_csv('https://raw.githubusercontent.com/jimmyzac/Estadistica-Aplicada-FCFM-UANL/main/bases_datos/ventas2.csv')

In [27]:
ventas

      Año         Mes  Ventas  Gasto
0    2010       Enero    1056    533
1    2010     Febrero     910    496
2    2010       Marzo    1095    695
3    2010       Abril    1157    599
4    2010        Mayo     969    490
..    ...         ...     ...    ...
163  2023      Agosto    1759   1818
164  2023  Septiembre    2114   2142
165  2023     Octubre    2120   1767
166  2023   Noviembre    2102   1652
167  2023   Diciembre    2166   2192

[168 rows x 4 columns]

En caso de que una cantidad contenga decimales, debe estar redondeada a un decimal

2. Características del dataframe

In [28]:
#con código de python muestra cuantas filas y columnas tiene el dataframe y como se llaman las columnas
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Año     168 non-null    int64
 1   Mes     168 non-null    object
 2   Ventas  168 non-null    int64
 3   Gasto   168 non-null    int64
dtypes: int64(3), object(1)
memory usage: 5.4+ KB

In [29]:
ventas.shape

(168, 4)

In [30]:
#muestra las primeras 5 filas del dataframe
ventas.head()

    Año      Mes  Ventas  Gasto
0  2010    Enero    1056    533
1  2010  Febrero     910    496
2  2010    Marzo    1095    695
3  2010    Abril    1157    599
4  2010     Mayo     969    490

*ventas es una base de datos que contiene las ventas mensuales de una tienda X para los años 2010-2023*

3. Crea una nueva columna que se llame **Ganancias** y que contenga la diferencia entre ventas-gastos

In [31]:
## escribe aqui el código
ventas['Ganancias'] = ventas['Ventas']-ventas['Gasto']

In [32]:
ventas

      Año         Mes  Ventas  Gasto  Ganancias
0    2010       Enero    1056    533        523
1    2010     Febrero     910    496        414
2    2010       Marzo    1095    695        400
3    2010       Abril    1157    599        558
4    2010        Mayo     969    490        479
..    ...         ...     ...    ...        ...
163  2023      Agosto    1759   1818        -59
164  2023  Septiembre    2114   2142        -28
165  2023     Octubre    2120   1767        353
166  2023   Noviembre    2102   1652        450
167  2023   Diciembre    2166   2192        -26

[168 rows x 5 columns]

4. Encuentra el mes-año con las ganancias más altas

In [33]:
## escribe aqui el código
ventas.sort_values('Ganancias',ascending=False)

      Año        Mes  Ventas  Gasto  Ganancias
91   2017     Agosto    1680   1088        592
82   2016  Noviembre    1533    952        581
9    2010    Octubre    1124    563        561
3    2010      Abril    1157    599        558
69   2015    Octubre    1412    869        543
..    ...        ...     ...    ...        ...
161  2023      Junio    2120   2159        -39
157  2023    Febrero    2097   2137        -40
159  2023      Abril    1625   1679        -54
163  2023     Agosto    1759   1818        -59
160  2023       Mayo    2161   2262       -101

[168 rows x 5 columns]

In [35]:
ventas.iloc[0,[0,1]]

Año     2010
Mes    Enero
Name: 0, dtype: object

5. Calcula e imprime las ventas totales, gastos totales y ganancias totales de  todo el periodo\
Ejemplo de mensaje: **las ventas totales son: 5000**, etc

In [37]:
## escribe aqui el código

ventasT = np.sum(ventas['Ventas'])
gastosT = np.sum(ventas['Gasto'])
gananciasT = np.sum(ventas['Ganancias'])

print(f'las ventas totales son de:{ventasT} Los gastos totales son de: {gastosT} Las ganancias totales son de:{gananciasT}')

las ventas totales son de:235731 Los gastos totales son de: 181123 Las ganancias totales son de:54608

6. Calcula y muestra las ventas, gastos y ganancias para cada año

In [44]:
## escribe aqui el código
ventas.groupby('Año')['Ventas','Gasto','Ganancias'].sum()

<ipython-input-44-65130a8439d0>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  ventas.groupby('Año')['Ventas','Gasto','Ganancias'].sum()

      Ventas  Gasto  Ganancias
Año
2010   12015   6756       5259
2011   12778   7806       4972
2012   12965   8430       4535
2013   14037   8963       5074
2014   14922  10377       4545
2015   14951  10784       4167
2016   15376  11053       4323
2017   17189  12369       4820
2018   18325  14648       3677
2019   18204  14759       3445
2020   18917  16206       2711
2021   21057  17693       3364
2022   21692  18946       2746
2023   23303  22333        970

7. Calcula y muestra las ventas promedio mensuales del año 2015

In [51]:
## escribe aqui el código
##Pista: primero filtra para el año 2015, luego selecciona la columna ventas
Ventas2015 = ventas.query('Año == 2015')

In [56]:
Ventas2015.groupby('Mes')['Ventas'].mean().round(2)

Mes
Abril         1031.0
Agosto        1065.0
Diciembre     1156.0
Enero         1410.0
Febrero       1419.0
Julio         1469.0
Junio         1178.0
Marzo         1021.0
Mayo          1470.0
Noviembre     1264.0
Octubre       1412.0
Septiembre    1056.0
Name: Ventas, dtype: float64

8. Calcula e imprime las ventas totales y ventas promedio para los eneros. Es decir, para enero de 2010, enero de 2011, enero 2012, etc

In [68]:
## escribe aqui el código ventas totales
##Pista: primero filtra los meses de enero, luego selecciona la columna ventas
VentasEnero = ventas.query('Mes == "Enero"')
VentasTE = np.sum(VentasEnero['Ventas'])
print(f'Las ventas totales de los meses de enero son: {VentasTE}')

Las ventas totales de los meses de enero son: 20073

In [69]:
## escribe aqui el código ventas promedio
VentasPE = np.mean(VentasEnero['Ventas']).round(2)
print(f'Las ventas promedio de los meses de enero son: {VentasPE}')

Las ventas promedio de los meses de enero son: 1433.79

9. Calcula las ventas promedio por mes, y muestra los meses ordenados de menor a mayor según su promedio

In [80]:
## aqui va tu codigo
VentasMeses= pd.DataFrame(ventas.groupby('Mes')['Ventas'].mean().round(2))
VentasMeses.sort_values('Ventas')

             Ventas
Mes
Junio       1325.71
Septiembre  1347.36
Julio       1363.64
Octubre     1388.29
Marzo       1394.43
Febrero     1406.36
Mayo        1409.71
Diciembre   1416.64
Enero       1433.79
Agosto      1437.86
Noviembre   1456.64
Abril       1457.50